---
title: "wild_data"
format: html
editor_options: 
  chunk_output_type: console
  execute: 
    warning: false 
---

## Aquatic Vertebrate Population Study A.K.A "Wild Data"

```{r}
#| warning: false  
#| message: false
#Attach packages
library(tidyverse)
library(here)
library(janitor)

```

```{r}
#Read in data
mack_verts <- read_csv(here::here("data", "AS00601.csv"))

#Update variables to lower snake case
mack_verts <- mack_verts %>% 
  janitor::clean_names() 

names(mack_verts)

#Storing data
mc_wt_5 <- mack_verts[5, "weight"]
mc_wt_5

mc_length_8_20 <- mack_verts[8:20, "length1"]
mc_length_8_20

mc_dates <-mack_verts[ ,"sampledate"]

```

```{r}
#Make salamander subset using dplyr::filter

mc_salamanders <- mack_verts %>% filter(species == "DITE")
mc_salamanders

```

```{r}
#Create scatterplot

mc_salamanders_plot <- ggplot(data = mc_salamanders, 
                        aes(x = length1, y = weight)) +
  geom_point(aes(color = "green"), show.legend = FALSE) +
  theme_minimal() + 
  labs(title = "Pacific Giant Salamander Length(mm) by Weight(g) ", 
       x = "Length (mm)",
       y = "Weight (g)") + subtitle = 
  

  

mc_salamanders_plot
```

```{r}
#Create cutthroat plot 

mc_trout <-mack_verts %>% filter(species == "ONCL")
mc_trout

mc_trout_plot <- ggplot(data = mc_trout, 
                        aes(x = length1, y = weight)) +  
  geom_point(aes(color = "green"), show.legend = FALSE) +
  theme_minimal() + 
  labs(title = "Pacific Giant Salamander Length(mm) by Weight(g) ", 
       x = "Length (mm)",
       y = "Weight (g)") + subtitle = 
  
  geom_point() 

```

